### ISSUE TITLE
param user

### ISSUE THREAD

**Issue by Kucklovod00** [waylaidwanderer/node-chatgpt-api#62] opened 2023-02-12 12:56 UTC
![image](https://user-images.githubusercontent.com/46756368/218312304-db9cc4e0-fe59-457f-881d-3a186439801a.png)

please add "user" parameter

**Comment by waylaidwanderer** [comment] 2023-02-12 13:27
Please explain your use-case

**Comment by Kucklovod00** [comment] 2023-02-12 15:23
What do you mean?

**Comment by waylaidwanderer** [comment] 2023-02-12 20:57
I mean why do you need to do this?

**Comment by Kucklovod00** [comment] 2023-02-12 21:27
to identify users and in case of violations of the rules, chatgpt will notify me

**Comment by waylaidwanderer** [comment] 2023-02-12 21:35
Are you using text-davinci-003 then? It's not really applicable for other models.

**Comment by Kucklovod00** [comment] 2023-02-13 23:52
> Вы используете text-davinci-003? Для других моделей это не совсем применимо.

yes

**Comment by waylaidwanderer** [comment] 2023-02-14 02:17
Okay, I'll make a note. Closing this as a duplicate of #28 as it can be part of the same enhancement.

**Closed by waylaidwanderer** 2023-02-14 02:17 UTC
