### ISSUE TITLE
Can't Connect bing , it return UnauthorizedRequest 

### ISSUE THREAD

**Issue by eu09** [waylaidwanderer/node-chatgpt-api#92] opened 2023-02-17 12:10 UTC
I will put my cookie as below example , but when I make a request it returns

cookies: 'KievRPSSecAuth=FACCBBRaTOJILtFsMkpLVWSG6AN6C/svRwNmAAAEgAAACDQZamaij4uHQATExm56h4hy80Fo/itiFqB3RuP7eNkFtsvexQqw7VWD0xAxvfw1CTii9Gq11wJ6qi93WuBEiN4b6YZ7ZH6FljFEO06nNgW/L1isCLUTJzipRJxDkmKFNx8HkN6xhWyfwdZ6u+cGVm1aK9LKx+OxOkUWi31a1X+X7ZKpjSnz64Nbcc

(Use `node --trace-warnings ...` to show where the warning was created)
today at 20:02:23{
today at 20:02:23  result: {
today at 20:02:23    value: 'UnauthorizedRequest',
today at 20:02:23    message: 'Sorry, you need to login first to access this service.'
today at 20:02:23  }
today at 20:02:23}
today at 20:02:23Error: UnauthorizedRequest: Sorry, you need to login first to access this service.
today at 20:02:23    at BingAIClient.sendMessage (file:///var/chatgpt-api/src/BingAIClient.js:125:23)
today at 20:02:23    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
today at 20:02:23    at async Object.<anonymous> (file:///var/chatgpt-api/bin/server.js:97:18)

**Comment by waylaidwanderer** [comment] 2023-02-17 12:17
Duplicate of #89

**Closed by waylaidwanderer** 2023-02-17 12:17 UTC
