### ISSUE TITLE
 That model is currently overloaded with other requests. 

### ISSUE THREAD

**Issue by theLastWinner** [waylaidwanderer/node-chatgpt-api#34] opened 2023-02-09 02:55 UTC
when i test it ,it show that :
```
Error: Failed to send message. HTTP 503 - {
  "error": {
    "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Ple
ase include the request ID 169bee8d  in your message.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}

```

**Comment by warrenrezane** [comment] 2023-02-09 03:01
Which model are you using? Is that, `text-chat-davinci-002-20221122`?

**Comment by theLastWinner** [comment] 2023-02-09 03:10
> Which model are you using? Is that, `text-chat-davinci-002-20221122`?

yes ,the request text is 
```
 model: 'text-chat-davinci-002-20221122',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  stop: [ '<|im_end|>', '<|im_sep|>', '\nUser:' ],
  max_tokens: 1000,
  stream: true,
  prompt: '\n' +
    '<|im_sep|>Instructions:\n' +
    'You are ChatGPT, a large language model trained by OpenAI.\n' +
    'Current date: February 9, 2023<|im_sep|>\n' +
    '\n' +
    'User:\n' +
    '怎么跑步更健康<|im_sep|>\n' +
    'ChatGPT:\n'
```

**Comment by waylaidwanderer** [comment] 2023-02-09 04:07
Duplicate of #32

**Closed by waylaidwanderer** 2023-02-09 04:07 UTC
