### ISSUE TITLE
question about  UND_ERR_CONNECT_TIMEOUT  

### ISSUE THREAD

**Issue by yuwangi** [waylaidwanderer/node-chatgpt-api#144] opened 2023-03-02 15:04 UTC
![image](https://user-images.githubusercontent.com/13346477/222466141-51f32411-7481-4417-908d-bcde65b14213.png)
All server requests are this error, and it can be started locally. Do you know the reason?

**Comment by waylaidwanderer** [comment] 2023-03-02 22:21
What client are you using? Additionally, can you show me your settings.js if you use the API server?

**Comment by yuwangi** [comment] 2023-03-02 23:51
@waylaidwanderer 
For some reasons, I need to build a reverse proxy by myself. Is there any code that can be easily deployed?

**Comment by waylaidwanderer** [comment] 2023-03-03 00:19
Not that I know of. So you're saying the issue is due to your internet connection?

**Comment by yuwangi** [comment] 2023-03-03 00:23
Yes, my country is blocked, I can only proxy through foreign servers

**Comment by yuwangi** [comment] 2023-03-03 00:34
I have a Korean server and want to use it for proxy

**Comment by waylaidwanderer** [comment] 2023-03-03 00:54
Is the Korean server why you're getting UND_ERR_CONNECT_TIMEOUT? Or is this a new topic?

**Comment by yuwangi** [comment] 2023-03-03 00:56
No, for some reasons, the domestic server api.openai.com is banned

**Comment by yuwangi** [comment] 2023-03-03 00:57
So I want to set up a reverse proxy, through the Korean server

**Comment by aiqinxuancai** [comment] 2023-03-03 02:47
> Is the Korean server why you're getting UND_ERR_CONNECT_TIMEOUT? Or is this a new topic?

I also have this problem with ChatGPTClient here, as far as I can see, it is an intermittent exception, maybe 1 minute in 10 minutes is completely normal, then the rest of the time all connections time out, this should not be a code level problem.
I think ChatGPTClient should also add “proxy” to its settings.

**Comment by yuwangi** [comment] 2023-03-03 02:57
No ,ChatGPTClient not included in the proxy ，You can try curl api.openai.com it is connection timeout  ，Because the server is blocked

**Comment by yuwangi** [comment] 2023-03-03 03:00
You can read this article    https://zh.wikipedia.org/zh-hans/%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E

**Comment by waylaidwanderer** [comment] 2023-03-03 05:33
I think this can be closed if #146 is merged.

**Comment by flyoverGu** [comment] 2023-03-03 06:01
昨晚上好像域名被屏蔽了。
自己动手改下ChatGPTClient.js
<img width="420" alt="image" src="https://user-images.githubusercontent.com/8547244/222643382-262b9e5c-4af0-496f-87e4-935ae0672e2d.png">
<img width="494" alt="image" src="https://user-images.githubusercontent.com/8547244/222643412-34cd7ec5-9c62-4379-b667-3f08d645bb41.png">
后续我看作者也会支持代理了，临时改改

**Comment by yuwangi** [comment] 2023-03-03 06:05
@flyoverGu  thanks~  I have solved it in other ways

**Comment by clippers1** [comment] 2023-03-03 09:59
@yuwangi how to solve

**Comment by yuwangi** [comment] 2023-03-03 10:02
Forwarding through a three-party server by socket

**Comment by pfeducode** [comment] 2023-03-04 05:40
i have  same probelm, what's reason?   i try to use vpn but it does not work.
![Uploading image.png…]()

**Comment by waylaidwanderer** [comment] 2023-03-06 00:30
Proxy support has been added in https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.26.0 which should fix this.

**Closed by waylaidwanderer** 2023-03-06 00:30 UTC
