### ISSUE TITLE
I faced 404 That model does not exist

### ISSUE THREAD

**Issue by gavin1818** [waylaidwanderer/node-chatgpt-api#131] opened 2023-02-28 16:11 UTC
Hello there, I faced the error message, any clue thanks
```
https://api.openai.com/v1/completions
{
  model: 'text-chat-davinci-002-sh-alpha-aoruigiofdj83',
  temperature: 0.8,
  top_p: 1,
  presence_penalty: 1,
  stop: [ '<|im_end|>', '<|im_sep|>', '\nUser:' ],
  max_tokens: 1024,
  prompt: '\n' +
    '<|im_sep|>Instructions:\n' +
    'You are ChatGPT, a large language model trained by OpenAI.\n' +
    'Current date: February 28, 2023<|im_sep|>\n' +
    '\n' +
    'User:\n' +
    'Hello, how are you today?<|im_end|>\n' +
    'ChatGPT:\n'
}

Error: Failed to send message. HTTP 404 - {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

    at ChatGPTClient.getCompletion (file:///Users/safasdf/workspace/node-chatgpt-api/src/ChatGPTClient.js:172:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ChatGPTClient.sendMessage (file:///Users/safasdf/workspace/node-chatgpt-api/src/ChatGPTClient.js:232:22)
    at async Object.<anonymous> (file:///Users/safasdf/workspace/node-chatgpt-api/bin/server.js:113:18) {
  status: 404,
  json: {
    error: {
      message: 'That model does not exist',
      type: 'invalid_request_error',
      param: null,
      code: null
    }
  }
}

```

**Comment by asus12345AVAIALBALEELELEL** [comment] 2023-02-28 17:43
This model has been patched/deleted, so you'll need to use `text-davinci-003` (which it's paid) or use  `ChatGPTBrowserClient` instead. (you have to provide accessToken else it won't work)

**Comment by waylaidwanderer** [comment] 2023-03-01 00:42
Duplicate of #115

**Closed by waylaidwanderer** 2023-03-01 00:42 UTC
