### ISSUE TITLE
UND_ERR_CONNECT_TIMEOUT There was an error communicating with ChatGPT.

### ISSUE THREAD

**Issue by ferrymo** [waylaidwanderer/node-chatgpt-api#171] opened 2023-03-07 13:33 UTC
已经挂到美区，官网api可以正常访问，该服务无法使用
`
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///E:/project/gitHubProject/node-chatgpt-api/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:52:34) {        
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (E:\project\gitHubProject\node-chatgpt-api\node_modules\undici\lib\core\connect.js:182:24)
      at E:\project\gitHubProject\node-chatgpt-api\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (E:\project\gitHubProject\node-chatgpt-api\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:471:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
`

**Comment by waylaidwanderer** [comment] 2023-03-07 21:13
Duplicate of #144?

**Comment by Godofcong-1** [comment] 2023-03-08 10:13
I also encountered a similar situation where I was able to run **BingAiClient**, but when using **ChatGptClient**, I encountered an _UND_ERR_CONNECT_TIMEOUT_ . With the use of proxy, the **use-client.js** in **demos** was able to run successfully and obtain a reply. However, when using the same proxy in **settings.js**, it resulted in an _UND_ERR_CONNECT_TIMEOUT_ .

**Comment by waylaidwanderer** [comment] 2023-03-08 11:07
@Godofcong-1 sounds like you possibly set the proxy in the wrong place in settings.js?

**Comment by Godofcong-1** [comment] 2023-03-09 02:11
Thank you for your reply. The Bing-related content in this project has helped me greatly.
This is where I set the proxy in **settings.js**. For the convenience of observation, I deleted the commented content, which remains unchanged in the actual code.
I set it in the same position of clientOptions in **use-client.js**.

>     chatGptClient: {
>         modelOptions: {
>             // You can override the model name and any other parameters here.
>             // The default model is `gpt-3.5-turbo`.
>             model: 'gpt-3.5-turbo',
>         },
>         // A proxy string like "http://<ip>:<port>"
>         proxy: 'http://127.0.0.1:7890',
>         // (Optional) Set to true to enable `console.debug()` logging
>         debug: false,
>     },

**Comment by ryanwy** [comment] 2023-03-10 02:35
same issue even with proxy

**Comment by waylaidwanderer** [comment] 2023-03-10 03:46
Not really sure what the issue is, tbh. I can't reproduce it on my end.

If possible, please create a minimally reproducible test repo in a new issue, and I'll check it out.

I'm closing this issue since OP hasn't responded, and it's hard to say whether or not you guys are having the same issue or a different issue with the same symptoms.

**Closed by waylaidwanderer** 2023-03-10 03:46 UTC

**Comment by pfeducode** [comment] 2023-03-12 15:09
> http://127.0.0.1:7890

You and I are using the same VPN, and I also use this port forwarding method, which works successfully.

**Comment by pfeducode** [comment] 2023-03-12 15:09
> 感谢你的回复。这个项目中Bing相关的内容对我帮助很大。**这是我在settings.js** 中设置代理的地方。为了方便观察，我删除了注释的内容，在实际代码中保持不变。**我在use-client.js** 中将它设置在与 clientOptions 相同的位置。********
> 
> > ```
> > chatGptClient: {
> >     modelOptions: {
> >         // You can override the model name and any other parameters here.
> >         // The default model is `gpt-3.5-turbo`.
> >         model: 'gpt-3.5-turbo',
> >     },
> >     // A proxy string like "http://<ip>:<port>"
> >     proxy: 'http://127.0.0.1:7890',
> >     // (Optional) Set to true to enable `console.debug()` logging
> >     debug: false,
> > },
> > ```

You and I are using the same VPN, and I also use this port forwarding method, which works successfully.
