### ISSUE TITLE
/turing/conversation/create: failed to parse response body.

### ISSUE THREAD

**Issue by PhineasZ** [waylaidwanderer/node-chatgpt-api#239] opened 2023-03-25 09:39 UTC
at BingAIClient.createNewConversation (file:///opt/gpt/node-chatgpt-api-1.32.0/src/BingAIClient.js:74:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async BingAIClient.sendMessage (file:///opt/gpt/node-chatgpt-api-1.32.0/src/BingAIClient.js:168:51)
at async Object.<anonymous> (file:///opt/gpt/node-chatgpt-api-1.32.0/bin/server.js: 100:18)

**Comment by PhineasZ** [comment] 2023-03-25 09:39
at BingAIClient.createNewConversation (file:///opt/gpt/node-chatgpt-api-1.32.0/src/BingAIClient.js:74:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.sendMessage (file:///opt/gpt/node-chatgpt-api-1.32.0/src/BingAIClient.js:168:51)
    at async Object.<anonymous> (file:///opt/gpt/node-chatgpt-api-1.32.0/bin/server.js:100:18)

**Comment by waylaidwanderer** [comment] 2023-03-25 09:51
Duplicate of #205

**Closed by waylaidwanderer** 2023-03-25 09:51 UTC
