### ISSUE TITLE
model does not exist

### ISSUE THREAD

**Issue by kelchy** [waylaidwanderer/node-chatgpt-api#133] opened 2023-03-01 06:04 UTC
anyone got non-proxy chatgpt client working?
i am getting "message: That model does not exist"
tried different models:
1. default
2. text-davinci-002-render-next
3. text-davinci-003
4. text-chat-davinci-002-20221122

all wont work

**Comment by waylaidwanderer** [comment] 2023-03-01 07:52
Duplicate of #115

**Comment by waylaidwanderer** [comment] 2023-03-01 07:53
@kelchy Make sure you set `text-davinci-003` (the only working model) under `modelOptions.model` for the `ChatGPTClient` options.

**Closed by waylaidwanderer** 2023-03-01 07:52 UTC
